[project]
name = "megatransfer"
version = "1.0.0"
requires-python = ">=3.13"

dependencies = [
    "pillow>=12.0.0",
    "playwright>=1.57.0",
    "pystray>=0.19.5",
    "python-dotenv>=1.2.1",
    "watchdog>=6.0.0",
]

[dependency-groups]
dev = [
    "coverage>=7.13.0",
    "pyinstaller>=6.17.0",
    "pyright>=1.1.407",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.14.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.pyright]
typeCheckingMode = "standard"
pythonVersion = "3.13"
include = ["app", "service", "utils", "tests"]
exclude = ["scripts"]
reportMissingTypeStubs = false
reportUnusedVariable = true
reportUnusedImport = true